name: sample_ww_data
description: Sample project to RND Web Workers
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  freezed: ^2.2.0
  json_annotation: ^4.8.0
  collection: ^1.17.0

dev_dependencies:
  build_runner: any
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.0