name: sample_ww
description: Sample project to RND Web Workers
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.9

dependencies:
  bloc: ^8.1.0
  flutter: 
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations: 
    sdk: flutter
  freezed: ^2.2.0
  intl: ^0.17.0
  js: ^0.6.5
  sample_ww_data: 
    path: ./example

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: any
  freezed_annotation: ^2.2.0
  intl_utils: ^2.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
